/**
 * Turns the supplied DRU International logo into site assets.
 *
 *   node scripts/build-brand.mjs <source.png>
 *
 * The artwork already ships with a transparent background, so the only work is
 * trimming to the ink, producing the sizes the site uses, and reporting the
 * exact brand colours so the palette can be derived from the mark rather than
 * eyeballed.
 */
import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = process.argv[2];
if (!SRC) {
  console.error("usage: node scripts/build-brand.mjs <source.png>");
  process.exit(1);
}

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "public", "images", "brand");
await mkdir(OUT, { recursive: true });

const WORK = 1600;

const { data, info } = await sharp(SRC)
  .resize({ width: WORK, withoutEnlargement: true })
  .ensureAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });
const { width: W, height: H } = info;

// --- trim to the visible ink ----------------------------------------------
let x0 = W, y0 = H, x1 = 0, y1 = 0;
for (let i = 0, q = 3; i < W * H; i++, q += 4) {
  if (data[q] < 24) continue; // effectively transparent
  const x = i % W, y = (i / W) | 0;
  if (x < x0) x0 = x;
  if (x > x1) x1 = x;
  if (y < y0) y0 = y;
  if (y > y1) y1 = y;
}
if (x1 < x0 || y1 < y0) throw new Error("no opaque pixels found in source");
const box = { left: x0, top: y0, width: x1 - x0 + 1, height: y1 - y0 + 1 };

// Materialise the trimmed artwork once. sharp allows a single extract per
// pipeline stage, so chaining resize/extract/resize/extract would fail.
const trimmed = await sharp(SRC)
  .resize({ width: WORK, withoutEnlargement: true })
  .extract(box)
  .png()
  .toBuffer();

/**
 * Flat vector-style artwork, so a quantised palette PNG is a fraction of the
 * truecolour size with no visible loss. These load during the intro, where
 * weight is felt directly.
 */
const png = { compressionLevel: 9, palette: true, quality: 92 };

// Full lockup, transparent — works on the dark surfaces and on light.
const full = await sharp(trimmed)
  .resize({ width: 720, withoutEnlargement: true })
  .png(png)
  .toFile(path.join(OUT, "logo-lockup.png"));

// "INTERNATIONAL" is unreadable below ~64px, so the compact mark used in tight
// spots is the DRU monogram only. The split is measured, not hard-coded.
const mono = await sharp(trimmed)
  .extract({
    left: 0,
    top: 0,
    width: box.width,
    height: Math.round(box.height * 0.82),
  })
  .resize({ width: 520, withoutEnlargement: true })
  .png(png)
  .toFile(path.join(OUT, "logo-monogram.png"));

// --- brand colours ---------------------------------------------------------
const buckets = new Map();
let whitePx = 0;
for (let i = 0, p = 0; i < W * H; i++, p += 4) {
  if (data[p + 3] < 200) continue;
  const r = data[p], g = data[p + 1], b = data[p + 2];
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  if (min > 230) {
    whitePx++;
    continue;
  }
  if (max < 60 || (max - min) / max < 0.45) continue;
  const key = `${r >> 3}_${g >> 3}_${b >> 3}`;
  const e = buckets.get(key) ?? { n: 0, r: 0, g: 0, b: 0 };
  e.n++; e.r += r; e.g += g; e.b += b;
  buckets.set(key, e);
}
const hex = (n) => Math.round(n).toString(16).padStart(2, "0");
const colours = [...buckets.values()]
  .sort((a, b) => b.n - a.n)
  .slice(0, 6)
  .map((e) => ({
    hex: `#${hex(e.r / e.n)}${hex(e.g / e.n)}${hex(e.b / e.n)}`,
    px: e.n,
  }));

/** Most-used colour whose dominant channel is `ch` (1 = green, 2 = blue). */
function pickByChannel(ch) {
  const hit = colours.find((c) => {
    const v = [1, 3, 5].map((i) => parseInt(c.hex.slice(i, i + 2), 16));
    return v.indexOf(Math.max(...v)) === ch;
  });
  return (hit ?? colours[0]).hex;
}

// Emit the intrinsic sizes as code so the components can never drift from the
// files on disk.
const GEN = path.join(ROOT, "src", "data", "generated");
await mkdir(GEN, { recursive: true });
await writeFile(
  path.join(GEN, "brand.ts"),
  `// GENERATED by scripts/build-brand.mjs -- do not edit by hand.

export const BRAND_LOCKUP = {
  src: "/images/brand/logo-lockup.png",
  width: ${full.width},
  height: ${full.height},
} as const;

export const BRAND_MONOGRAM = {
  src: "/images/brand/logo-monogram.png",
  width: ${mono.width},
  height: ${mono.height},
} as const;

/** Sampled from the artwork; mirrored by --color-brand-* in globals.css. */
export const BRAND_COLOURS = {
  blue: "${pickByChannel(2)}",
  green: "${pickByChannel(1)}",
} as const;
`,
);

console.log(`source        ${path.basename(SRC)} (${W}x${H} working)`);
console.log(`ink bbox      ${box.width}x${box.height}`);
console.log(`logo-lockup   ${full.width}x${full.height}`);
console.log(`logo-monogram ${mono.width}x${mono.height}`);
console.log(`opaque white  ${whitePx.toLocaleString()} px (the globe's continents)`);
console.log(`\ndominant brand colours:`);
for (const c of colours) console.log(`  ${c.hex}  ${c.px.toLocaleString()} px`);
